export const SurveyActionTypes = {
    REQUEST_PROCCESS = "REQUEST_PROCCESS",
    REQUEST_ERROR = "REQUEST_ERROR",
    SURVEY_REQUEST_SUCCESS = "SURVEY_REQUEST_SUCCESS",
    SURVEYS_REQUEST_SUCCESS = "SURVEYS_REQUEST_SUCCESS",
    MODIFY_SURVEY_REQUEST_SUCCESS = "MODIFY_SURVEY_REQUEST_SUCCESS",
    RESPONSE_REQUEST_SUCCESS = "RESPONSE_REQUEST_SUCCESS",
    RESPONSES_REQUEST_SUCCESS = "RESPONSES_REQUEST_SUCCESS",
    MODIFY_RESPONSE_REQUEST_SUCCESS = "MODIFY_RESPONSE_REQUEST_SUCCESS",
    RESPONSE_LINK_REQUEST_SUCCESS = "RESPONSE_LINK_REQUEST_SUCCESS",
}