const QuestionActionTypes = {
    ADD_QUESTION: 'ADD_QUESTION',
    REMOVE_QUESTION: 'REMOVE_QUESTION',
    SET_FORMAT: 'SET_FORMAT',
    TOGGLE_REQUIRED: 'TOGGLE_REQUIRED',
    SET_TITLE: 'SET_TITLE',
    SET_CURRENTID: 'SET_CURRENTID'
}

export default QuestionActionTypes;