const QuestionActionTypes = {
    RESET_QUESTIONS: 'RESET_QUESTIONS',
    ADD_QUESTION: 'ADD_QUESTION',
    REMOVE_QUESTION: 'REMOVE_QUESTION',
    SET_FORMAT: 'SET_FORMAT',
    TOGGLE_REQUIRED: 'TOGGLE_REQUIRED',
    SET_TITLE: 'SET_TITLE',
    SET_CURRENTID: 'SET_CURRENTID',
    ADD_TO_QUESTION_COLLECTION: 'ADD_TO_QUESTION_COLLECTION',
    UPDATE_QUESTIONS: 'UPDATE_QUESTIONS',
}

export default QuestionActionTypes;