const ReportActionTypes = {
    FETCH_ALL_REPORT: "FETCH_ALL_REPORT",
    FETCH_A_SINGLE_REPORT: "FETCH_A_SINGLE_REPORT",
    MANAGE_DESCRIPTION_TAB_DISPLAY: "MANAGE_DESCRIPTION_TAB_DISPLAY",
    MANAGE_GOALS_AND_OBJECTIVE_TAB_DISPLAY: "MANAGE_GOALS_AND_OBJECTIVE_TAB_DISPLAY",
    MANAGE_TEAM_TAB_DISPLAY: "MANAGE_TEAM_TAB_DISPLAY",
    MANAGE_DATE_AND_MILESTONE_TAB_DISPLAY: "MANAGE_DATE_AND_MILESTONE_TAB_DISPLAY",
    MANAGE_SCOPE_TAB_DISPLAY: "MANAGE_SCOPE_TAB_DISPLAY",
    MANAGE_EXECUTION_PLAN_TAB_DISPLAY: "MANAGE_EXECUTION_PLAN_TAB_DISPLAY",
    MANAGE_RESOURCE_REQUIREMENT_TAB_DISPLAY: "MANAGE_RESOURCE_REQUIREMENT_TAB_DISPLAY",
    MANAGE_SURVEY_INFORMATION_TAB_DISPLAY: "MANAGE_SURVEY_INFORMATION_TAB_DISPLAY",
    MANAGE_BUDGET_TAB_DISPLAY: "MANAGE_BUDGET_TAB_DISPLAY",
}
export default ReportActionTypes