export const ProjectActionTypes = {
    REQUEST_PROCESS: "REQUEST_PROCESS",
    REQUEST_ERROR: "REQUEST_ERROR",
    PROJECTS_REQUEST_SUCCESS: "PROJECTS_REQUEST_SUCCESS",
    PROJECT_REQUEST_SUCCESS: "PROJECT_REQUEST_SUCCESS",
    MODIFY_PROJECT_REQUEST_SUCCESS: "MODIFY_PROJECT_REQUEST_SUCCESS",

}